"""empty message

Revision ID: 04ef0dbcbfc8
Revises: 4dd7e1e0dc33
Create Date: 2025-05-14 18:06:39.932201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ef0dbcbfc8'
down_revision = '4dd7e1e0dc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblockedlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokenblockedlist')
    # ### end Alembic commands ###
