"""empty message

Revision ID: 2689b5bd3a41
Revises: f99e0ec63184
Create Date: 2025-05-28 11:00:12.392973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2689b5bd3a41'
down_revision = 'f99e0ec63184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.drop_constraint('users_firebase_uid_key', type_='unique')
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_firebase_uid_key', ['firebase_uid'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
