"""empty message

Revision ID: 4295bf305e73
Revises: 8ff18c7274ac
Create Date: 2025-06-06 18:15:01.059123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4295bf305e73'
down_revision = '8ff18c7274ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('fullname', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=300), nullable=True))
        batch_op.drop_constraint('users_firebase_uid_key', type_='unique')
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('firebase_uid')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('firebase_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_username_key', ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('users_firebase_uid_key', ['firebase_uid'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('fullname')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
