"""empty message

Revision ID: 643f5d741de7
Revises: 73d6aece5bd9
Create Date: 2025-05-10 10:44:52.055899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643f5d741de7'
down_revision = '73d6aece5bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('reportes_text_key', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('reportes_text_key', ['text'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
