"""empty message

Revision ID: 6b1b7d700c5a
Revises: b0b9e0a375d7
Create Date: 2025-06-11 22:48:45.846611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1b7d700c5a'
down_revision = 'b0b9e0a375d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moderator', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_moderator')

    # ### end Alembic commands ###
