"""empty message

Revision ID: 6d1af188c3e2
Revises: 04ef0dbcbfc8
Create Date: 2025-05-28 10:45:09.866563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1af188c3e2'
down_revision = '04ef0dbcbfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['firebase_uid'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
