"""empty message

Revision ID: b0b9e0a375d7
Revises: a046775fc9cb
Create Date: 2025-06-11 16:17:48.434784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b9e0a375d7'
down_revision = 'a046775fc9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
