"""empty message

Revision ID: d490d58ef8d6
Revises: bc6c87db2253
Create Date: 2025-06-12 00:23:58.038634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd490d58ef8d6'
down_revision = 'bc6c87db2253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('denuncias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denunciante_id', sa.Integer(), nullable=False),
    sa.Column('denunciado_id', sa.Integer(), nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['denunciado_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['denunciante_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('denuncias')
    op.drop_table('sanciones')
    # ### end Alembic commands ###
